#!/bin/bash

# Set environment variables
export HOUSE_NAME="house1"
export ROOM_NAME="room2"
export DEVICE_NAME="device2"
set PORT=33002
export BROADCAST_PORT=33000
export SENSOR_TYPE='speed'

# You can also run any command that needs these environment variables now
# For example:
# ./some_command_that_uses_env_vars
